version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: messaging_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app:
    build: .
    command: ./main serve-http
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - CONFIG_PATH=package/config/config.yaml
    volumes:
      - ./config:/root/config
      - ./migrations:/root/migrations
      - ./package/config/config.yaml:/app/package/config/config.yaml


volumes:
  postgres_data:
  rabbitmq_data: